#pragma once

#ifdef __linux__
#define ENABLE_RAND_PORT
#endif

#ifdef RELEASE
#define ONLINE_SERVER_PORT 7500
#else
#ifdef ENABLE_RAND_PORT
extern int ONLINE_SERVER_PORT;
#else
#define ONLINE_SERVER_PORT 7501
#endif
#endif
#define ONLINE_SERVER_MIN_USERNAME_LEN 4
#define ONLINE_SERVER_MAX_USERNAME_LEN 24
#define ONLINE_SERVER_MIN_CHAT_LEN 1
#define ONLINE_SERVER_MAX_CHAT_LEN 500
#define ONLINE_SERVER_ALLOWED_NAME_CHARS " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
